// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBltv5AzuymxaIGMu9yHKns66V72uDnUKI',
    appId: '1:807286810952:web:4e9b290be82fe5a19eab7d',
    messagingSenderId: '807286810952',
    projectId: 'salary-planner-d251f',
    authDomain: 'salary-planner-d251f.firebaseapp.com',
    storageBucket: 'salary-planner-d251f.firebasestorage.app',
    measurementId: 'G-B3PKW8GX0D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6h94F5ZdGIw0ILCWiJ_2nBk6BX_AdmnM',
    appId: '1:807286810952:android:5c3848dfa01595a59eab7d',
    messagingSenderId: '807286810952',
    projectId: 'salary-planner-d251f',
    storageBucket: 'salary-planner-d251f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1EO42DEePhKlkNQSs5Yx0YN8sTm7oeP4',
    appId: '1:807286810952:ios:b7100c485324f9689eab7d',
    messagingSenderId: '807286810952',
    projectId: 'salary-planner-d251f',
    storageBucket: 'salary-planner-d251f.firebasestorage.app',
    iosClientId: '807286810952-hqtsvr76ti3u7ta544ishbnjb36o829j.apps.googleusercontent.com',
    iosBundleId: 'com.example.salaryplanner.salaryPlanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1EO42DEePhKlkNQSs5Yx0YN8sTm7oeP4',
    appId: '1:807286810952:ios:b7100c485324f9689eab7d',
    messagingSenderId: '807286810952',
    projectId: 'salary-planner-d251f',
    storageBucket: 'salary-planner-d251f.firebasestorage.app',
    iosClientId: '807286810952-hqtsvr76ti3u7ta544ishbnjb36o829j.apps.googleusercontent.com',
    iosBundleId: 'com.example.salaryplanner.salaryPlanner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBltv5AzuymxaIGMu9yHKns66V72uDnUKI',
    appId: '1:807286810952:web:7483ef221f0b2a169eab7d',
    messagingSenderId: '807286810952',
    projectId: 'salary-planner-d251f',
    authDomain: 'salary-planner-d251f.firebaseapp.com',
    storageBucket: 'salary-planner-d251f.firebasestorage.app',
    measurementId: 'G-B81NCSXP77',
  );
}
